ame: build
on:
  pull_request:
  push:
    branches: [ main ]

jobs: 
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - run: |
           download_url="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz" wget -O $RUNNER_TEMP/java_package.tar.gz $download_url 
      - uses: actions/setup-java@v3
        with:
            distribution: 'jdkfile'
            jdkFile: ${{ runner.temp }}/java_package.tar.gz
            java-version: '11.0.0'
            architecture: x64  
      - run: java -cp java HelloWorldApp
      - run: java -cp java HelloWorldApp
      - name: Build and Run Test
        run: |
          chmod +x "${GITHUB_WORKSPACE}/TestScripts/SampleTest.sh"
          "${GITHUB_WORKSPACE}/TestScripts/SampleTest.sh"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
