name: build
on:
  pull_request:
  push:
    branches: [ main ]

jobs: 
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/checkout@v2
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '17.0.0'
          architecture: x64
          jdkFile: "${GITHUB_WORKSPACE}/TestScripts/App2
      - run: java -cp java App2
      - name: Build and Run Test
        run: |
          chmod +x "${GITHUB_WORKSPACE}/TestScripts/SampleTest.sh"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: "**/build/test-results/test/TEST-*.xml"
